### ISSUE TITLE
Website Language Filter C# broken

### ISSUE THREAD

**Issue by joshimoo** [kennyledet/Algorithm-Implementations#411]
The website seems to have a problem showing the c# algorithms. 
If you have a look at http://dry-sea-7022.herokuapp.com/language/12
 
You will see that bubblesort links to the c version:
https://github.com/kennyledet/Algorithm-Implementations/blob/master/Bubble_Sort/C/mitogh/bubble_sort.c

**Comment by joshimoo** [comment]
@kennyledet Thanks for your hard work. 
On the public site this issue is still remaining.
Do you have an internal version where this is fixed?

**Comment by kennyledet** [comment]
Thank you, and yes sir, it is fixed in the new core redesign of the web app. I was hoping on releasing it before March came but unfortunately my right hand got injured and it was kinda difficult for me to type as fast or efficiently, so I took a break. I'm still a bit busy helping my boss at work squash some bugs and deploy things, but realistically the app should be open sourced within the next couple weeks.

**Comment by kennyledet** [comment]
Fixed :)

http://algorithm.zone/language/12/scala

**Comment by joshimoo** [comment]
Hi Kenny, thanks for the hard work.
But for the c/c# language it still seems to not be working correctly.

For example Bubblesort: 
mitogh is shown as an author for bubblesort in C# as well as C even tough, he does not have a c# implementation.

The source code field is empty in the C# version since there is no source code.
It also seems as if all newer C# submissions don't show up either.
The show on github links seem to no longer work?

**Comment by kennyledet** [comment]
Hm, I didn't check that one, though I should have after checking Scala. Thanks for the heads up! I'll go through all languages today and make sure it's patched up completely 







Best regards,

Kendrick Ledet



—
